name: Elm CI

on: [push]

jobs:
  check-commit-message:
    name: check commit message if skipping build(s)
    runs-on: ubuntu-latest
    
    # skips CI and prints cli message, without fail build badge
    if: "contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: print message via cli
        run: echo "no need to build, based from commit message"
        
  build:
    name: Setup Elm and test it
    runs-on: ubuntu-latest
        
    # doesn't contain "ci skip" in commit message
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: clone repo
        uses: actions/checkout@v1

      - name: setup nodejs
        uses: actions/setup-node@v1
        
      - name: cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Elm, elm-format & elm-test
        run: |
          npm install -g elm elm-format elm-test
          elm-format src/ --yes
      - name: Install elm-format & elm-test
        run: elm-test
