name: Elm CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:alpine

    steps:
      - uses: actions/checkout@v1

      - name: Install Elm, elm-format & elm-test
        run: |
          npm install -g elm elm-format elm-test
          elm-format src/ --yes
      - name: Install elm-format & elm-test
        run: elm-test

